version: "3.8"
services:
  api:
    container_name: api-container
    restart: always
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  client:
    container_name: client-container
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
  mongo:
    container_name: mongo-backend
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
  torproxy:
    image: dperson/torproxy
    ports:
      - "8118:8118" 
      - "9050:9050"
volumes:
  mongo_db: