const sexualWordsArray = [
  "coition",
  "coitus",
  "copulation",
  "fornication",
  "intercourse",
  "intimacy",
  "love making",
  "procreation",
  "relations",
  "sex",
  "sex act",
  "sexual congress",
  "carnal embrace",
  "carnal knowledge",
  "coition",
  "congress",
  "copulation",
  "intercourse",
  "intimacy",
  "relation",
  "sex",
  "carnal knowledge",
  "coition",
  "coupling",
  "fooling around",
  "fornication",
  "intercourse",
  "intimacy",
  "lovemaking",
  "mating",
  "nooky",
  "procreation",
  "relations",
  "sex",
  "sexual intercourse",
  "sexual relations",
  "sexual union",
];
const gunsWords
