const labeledWords = [
  { keyWord: "love making", label: "sexual" },
  { keyWord: "sex act", label: "sexual" },
  { keyWord: "hot", label: "sexual" },
  { keyWord: "penis", label: "sexual" },
  { keyWord: "sex", label: "sexual" },
  { keyWord: "lovemaking", label: "sexual" },
  { keyWord: "mating", label: "sexual" },
  { keyWord: "porn", label: "sexual" },
  { keyWord: "nooky", label: "sexual" },
  { keyWord: "relations", label: "sexual" },
  { keyWord: "sex", label: "sexual" },
  { keyWord: "p0rnhub", label: "sexual" },
  { keyWord: "p0rn", label: "sexual" },
  { keyWord: " ❤️ ", label: "sexual" },
  { keyWord: "ammo", label: "violence" },
  { keyWord: "arms", label: "violence" },
  { keyWord: "arrow", label: "violence" },
  { keyWord: "assault rifle", label: "violence" },
  { keyWord: "army", label: "violence" },
  { keyWord: "ARMY", label: "violence" },
  { keyWord: "atom bomb", label: "violence" },
  { keyWord: "automatic rifle", label: "violence" },
  { keyWord: "axe", label: "violence" },
  { keyWord: "ballistic missile", label: "violence" },
  { keyWord: "battle axe", label: "violence" },
  { keyWord: "bayonet", label: "violence" },
  { keyWord: "bazooka", label: "violence" },
  { keyWord: "billy club", label: "violence" },
  { keyWord: "biological weapon", label: "violence" },
  { keyWord: "boobytrap", label: "violence" },
  { keyWord: "boomerang", label: "violence" },
  { keyWord: "brass knuckles", label: "violence" },
  { keyWord: "cannon", label: "violence" },
  { keyWord: "carbine", label: "violence" },
  { keyWord: "catapult", label: "violence" },
  { keyWord: "cleaver", label: "violence" },
  { keyWord: "club", label: "violence" },
  { keyWord: "crossbow", label: "violence" },
  { keyWord: "cudgel", label: "violence" },
  { keyWord: "cutlass", label: "violence" },
  { keyWord: "dagger", label: "violence" },
  { keyWord: "dart", label: "violence" },
  { keyWord: "depth charge", label: "violence" },
  { keyWord: "epee", label: "violence" },
  { keyWord: "explosives", label: "violence" },
  { keyWord: "firearm", label: "violence" },
  { keyWord: "flail", label: "violence" },
  { keyWord: "flamethrower", label: "violence" },
  { keyWord: "flintlock", label: "violence" },
  { keyWord: "foil", label: "violence" },
  { keyWord: "Gatling gun", label: "violence" },
  { keyWord: "grenade", label: "violence" },
  { keyWord: "grenade launcher", label: "violence" },
  { keyWord: "guided missile", label: "violence" },
  { keyWord: "gun", label: "violence" },
  { keyWord: "gunpowder", label: "violence" },
  { keyWord: "halberd", label: "violence" },
  { keyWord: "hand grenade", label: "violence" },
  { keyWord: "hatchet", label: "violence" },
  { keyWord: "howitzer", label: "violence" },
  { keyWord: "hunting knife", label: "violence" },
  { keyWord: "longsword", label: "violence" },
  { keyWord: "mace", label: "violence" },
  { keyWord: "machete", label: "violence" },
  { keyWord: "machine gun", label: "violence" },
  { keyWord: "magnum", label: "violence" },
  { keyWord: "maul", label: "violence" },
  { keyWord: "mine", label: "violence" },
  { keyWord: "missile", label: "violence" },
  { keyWord: "nerve gas", label: "violence" },
  { keyWord: "night stick", label: "violence" },
  { keyWord: "nuclear bomb", label: "violence" },
  { keyWord: "nunchaku", label: "violence" },
  { keyWord: "nunchucks", label: "violence" },
  { keyWord: "onager", label: "violence" },
  { keyWord: "ordnance", label: "violence" },
  { keyWord: "peashooter", label: "violence" },
  { keyWord: "pepper spray", label: "violence" },
  { keyWord: "pickaxe", label: "violence" },
  { keyWord: "pike", label: "violence" },
  { keyWord: "pistol", label: "violence" },
  { keyWord: "night stick", label: "violence" },
  { keyWord: "nuclear bomb", label: "violence" },
  { keyWord: "rifle", label: "violence" },
  { keyWord: "rocket", label: "violence" },
  { keyWord: "rocket launcher", label: "violence" },
  { keyWord: "saber", label: "violence" },
  { keyWord: "shooter", label: "violence" },
  { keyWord: "shotgun", label: "violence" },
  { keyWord: "sickle", label: "violence" },
  { keyWord: "slingshot", label: "violence" },
  { keyWord: "spear", label: "violence" },
  { keyWord: "spiked mace", label: "violence" },
  { keyWord: "stiletto", label: "violence" },
  { keyWord: "stun gun", label: "violence" },
  { keyWord: "sword", label: "violence" },
  { keyWord: "tank", label: "violence" },
  { keyWord: "tank gun", label: "violence" },
  { keyWord: "taser", label: "violence" },
  { keyWord: "truncheon", label: "violence" },
  { keyWord: "Uzi", label: "violence" },
  { keyWord: "weapon", label: "violence" },
  { keyWord: "weaponry", label: "violence" },
  { keyWord: "crypto", label: "money" },
  { keyWord: "bitcoin", label: "money" },
  { keyWord: "BTC", label: "money" },
  { keyWord: "btc", label: "money" },
  { keyWord: "credits", label: "money" },
  { keyWord: "\\$", label: "money" },
  { keyWord: "moneys", label: "money" },
  { keyWord: "resources", label: "money" },
  { keyWord: "advocate", label: "money" },
  { keyWord: "ally", label: "money" },
  { keyWord: "angel", label: "money" },
  { keyWord: "benefactor", label: "money" },
  { keyWord: "champion", label: "money" },
  { keyWord: "endorser", label: "money" },
  { keyWord: "follower", label: "money" },
  { keyWord: "grubstaker", label: "money" },
  { keyWord: "meal ticket", label: "money" },
  { keyWord: "money", label: "money" },
  { keyWord: "sponsor", label: "money" },
  { keyWord: "CD", label: "money" },
  { keyWord: "IRA", label: "money" },
  { keyWord: "business", label: "money" },
  { keyWord: "cash", label: "money" },
  { keyWord: "fortune", label: "money" },
  { keyWord: "funds", label: "money" },
  { keyWord: "gold", label: "money" },
  { keyWord: "investment", label: "money" },
  { keyWord: "means", label: "money" },
  { keyWord: "money", label: "money" },
  { keyWord: "savings", label: "money" },
  { keyWord: "stake", label: "money" },
  { keyWord: "stock", label: "money" },
  { keyWord: "substance", label: "money" },
  { keyWord: "treasure", label: "money" },
  { keyWord: "wealth", label: "money" },
  { keyWord: "wherewithal", label: "money" },
  { keyWord: "bread", label: "money" },
  { keyWord: "cash", label: "money" },
  { keyWord: "copper", label: "money" },
  { keyWord: "currency", label: "money" },
  { keyWord: "doubloon", label: "money" },
  { keyWord: "dough", label: "money" },
  { keyWord: "piece", label: "money" },
  { keyWord: "scratch", label: "money" },
  { keyWord: "cards", label: "money" },
  { keyWord: "silver", label: "money" },
  { keyWord: "small change", label: "money" },
  { keyWord: "specie", label: "money" },
  { keyWord: "cash", label: "money" },
  { keyWord: "credit", label: "money" },
  { keyWord: "btc", label: "money" },
  { keyWord: "hard cash", label: "money" },
  { keyWord: "database", label: "dataBase" },
  { keyWord: "databases", label: "dataBase" },
  { keyWord: "DB", label: "dataBase" },
];

module.exports = { labeledWords };
